import { useEffect, useState } from 'react'
import { Ban, CircleCheck, Clock3, RefreshCcw } from 'lucide-react'
import { useHydroShield } from '../state/HydroShieldContext'
import { formatModelName, formatStatus, formatStep } from '../utils/formatters'

const TERMINAL = new Set(['completed', 'failed', 'cancelled'])
function badge(status) { if (status === 'completed') return 'bg-emerald-100 text-emerald-800'; if (status === 'failed') return 'bg-rose-100 text-rose-800'; if (status === 'cancelled') return 'bg-slate-200 text-slate-700'; return 'bg-amber-100 text-amber-800' }
function Simulation() {
  const { jobs, refreshJob, refreshSimulations, cancelSimulation } = useHydroShield(); const [refreshing, setRefreshing] = useState(false)
  useEffect(() => { const active = jobs.filter((job) => !TERMINAL.has(job.status)); if (!active.length) return undefined; const id = window.setInterval(() => active.forEach((job) => refreshJob(job.id).catch(() => null)), 2500); return () => window.clearInterval(id) }, [jobs, refreshJob])
  async function refresh() { setRefreshing(true); try { const remoteJobs = await refreshSimulations(); await Promise.all(remoteJobs.map((job) => refreshJob(job.id).catch(() => null))) } finally { setRefreshing(false) } }
  const hasCompleted = jobs.some((job) => job.status === 'completed')
  const hasAnalysis = jobs.some((job) => job.result?.analysis_result_id)
  return <div className="space-y-4"><section className="flex items-end justify-between gap-4 rounded-[24px] border-2 border-sky-700/80 bg-sky-50/85 p-6"><div><div className="text-xs font-bold uppercase tracking-[0.14em] text-sky-700">Persistent worker queue</div><h1 className="mt-1 text-3xl font-black">Simulation Queue</h1><p className="mt-2 max-w-2xl text-sm font-medium text-slate-600">Real backend jobs expose status, progress, retries, cancellation and solver failures.</p></div><button type="button" onClick={refresh} className="flex items-center gap-2 rounded-xl border-2 border-sky-700/70 bg-white/50 px-3 py-2 text-sm font-bold"><RefreshCcw size={16} className={refreshing ? 'animate-spin' : ''} /> Refresh</button></section><div className="grid gap-4">{!jobs.length && <div className="rounded-2xl border-2 border-dashed border-sky-700/40 bg-white/50 p-8 text-center text-sm font-semibold text-slate-500">No simulation jobs yet. Start one from Dashboard.</div>}{jobs.map((job) => <div key={job.id} className="rounded-[20px] border-2 border-sky-700/70 bg-sky-50/80 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex gap-2"><span className="rounded-full bg-sky-100 px-3 py-1 text-xs font-bold text-sky-800">{formatModelName(job.model)}</span><span className={`rounded-full px-3 py-1 text-xs font-bold ${badge(job.status)}`}>{formatStatus(job.status)}</span></div><h2 className="mt-2 text-lg font-black">Job {job.id.slice(0, 8)}</h2><div className="mt-1 text-xs font-semibold text-slate-500">Scenario {job.scenario_id.slice(0, 8)} · Variant {job.variant_id.slice(0, 8)} · Attempt {job.attempt}/{job.max_attempts}</div></div>{!TERMINAL.has(job.status) && <button type="button" onClick={() => cancelSimulation(job.id)} className="flex items-center gap-2 rounded-xl border-2 border-rose-300 bg-rose-50 px-3 py-2 text-xs font-bold text-rose-800"><Ban size={15} /> Cancel</button>}</div><div className="mt-5 h-3 overflow-hidden rounded-full border border-sky-700/30 bg-sky-100"><div className="h-full rounded-full bg-gradient-to-r from-sky-400 to-sky-700 transition-all" style={{ width: `${Math.min(100, Math.max(0, job.progress))}%` }} /></div><div className="mt-2 flex justify-between text-xs font-bold text-slate-600"><span className="flex items-center gap-1.5">{job.status === 'completed' ? <CircleCheck size={14} /> : <Clock3 size={14} />} {formatStep(job.current_step)}</span><span>{Number(job.progress).toFixed(0)}%</span></div>{job.error_message && <div className="mt-3 rounded-xl border border-rose-300 bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-900">{job.error_message}</div>}</div>)}</div></div>
}
export default Simulation
